### ISSUE TITLE
How do you use this?11?!

### ISSUE THREAD

**Issue by ataulm** [mr-archano/static-analysis-plugin#1]
I adding this to my classpath build.gralde but it nothing happens?

what do I do? when does the plugin take?

**Comment by mr-archano** [comment]
The plugin applies Checkstyle, PMD, Lint (Android only) and JaCoCo under the hood when you apply it via `apply plugin: static-analysis` in your Java or Android module. I will amend the readme whit this information. Thanks for the pointer.

**Comment by ataulm** [comment]
Thank you!!1!!1! I have madr it work with apply plugin
